CREATE TABLE person_src (
    id BIGINT,
    name VARCHAR,
    emailAddress VARCHAR,
    creditCard VARCHAR,
    city VARCHAR,
    state VARCHAR,
    `dateTime` TIMESTAMP(3),
    extra VARCHAR,
    WATERMARK FOR `dateTime` AS `dateTime` - INTERVAL '4' SECOND,
    PRIMARY KEY (id) NOT ENFORCED
) WITH (
    'connector' = 'nexmark',
    'event.type' = 'person',
    'base-time' = '${BASE_TIME_MILLIS}',
    'first-event-id' = '${FIRST_EVENT_ID}',
    'first-event.rate' = '${TPS}',
    'next-event.rate' = '${TPS}',
    'events.num' = '${EVENTS_NUM}',
    'person.proportion' = '${PERSON_PROPORTION}',
    'auction.proportion' = '${AUCTION_PROPORTION}',
    'bid.proportion' = '${BID_PROPORTION}',
    'keep-alive' = '${KEEP_ALIVE}',
    'stop-at' = '${STOP_AT}',
    'max-emit-speed' = '${MAX_EMIT_SPEED}',
    'occasional-delay.min-sec' = '${OCCASIONAL_DELAY_MIN_SEC}',
    'occasional-delay.sec' = '${OCCASIONAL_DELAY_SEC}',
    'prob-delayed-event' = '${PROB_DELAYED_EVENT}',
    'out-of-order-group-size' = '${OUT_OF_ORDER_GROUP_SIZE}',
    'num-in-flight-auctions' = '${NUM_IN_FLIGHT_AUCTIONS}',
    'scan.watermark.emit.strategy' = 'on-event',
    'scan.watermark.idle-timeout' = '30s',
    'scan.watermark.alignment.group' = 'nexmark-events',
    'scan.watermark.alignment.max-drift' = '1s',
    'scan.watermark.alignment.update-interval' = '200ms'
);

CREATE TABLE auction_src (
    id BIGINT,
    itemName VARCHAR,
    description VARCHAR,
    initialBid BIGINT,
    reserve BIGINT,
    `dateTime` TIMESTAMP(3),
    expires TIMESTAMP(3),
    seller BIGINT,
    category BIGINT,
    extra VARCHAR,
    WATERMARK FOR `dateTime` AS `dateTime` - INTERVAL '4' SECOND,
    PRIMARY KEY (id) NOT ENFORCED
) WITH (
    'connector' = 'nexmark',
    'event.type' = 'auction',
    'base-time' = '${BASE_TIME_MILLIS}',
    'first-event-id' = '${FIRST_EVENT_ID}',
    'first-event.rate' = '${TPS}',
    'next-event.rate' = '${TPS}',
    'events.num' = '${EVENTS_NUM}',
    'person.proportion' = '${PERSON_PROPORTION}',
    'auction.proportion' = '${AUCTION_PROPORTION}',
    'bid.proportion' = '${BID_PROPORTION}',
    'keep-alive' = '${KEEP_ALIVE}',
    'stop-at' = '${STOP_AT}',
    'max-emit-speed' = '${MAX_EMIT_SPEED}',
    'occasional-delay.min-sec' = '${OCCASIONAL_DELAY_MIN_SEC}',
    'occasional-delay.sec' = '${OCCASIONAL_DELAY_SEC}',
    'prob-delayed-event' = '${PROB_DELAYED_EVENT}',
    'out-of-order-group-size' = '${OUT_OF_ORDER_GROUP_SIZE}',
    'num-in-flight-auctions' = '${NUM_IN_FLIGHT_AUCTIONS}',
    'scan.watermark.emit.strategy' = 'on-event',
    'scan.watermark.idle-timeout' = '30s',
    'scan.watermark.alignment.group' = 'nexmark-events',
    'scan.watermark.alignment.max-drift' = '1s',
    'scan.watermark.alignment.update-interval' = '200ms'
);

CREATE TABLE bid_src (
    id BIGINT,
    auction BIGINT,
    bidder BIGINT,
    price BIGINT,
    channel VARCHAR,
    url VARCHAR,
    `dateTime` TIMESTAMP(3),
    extra VARCHAR,
    WATERMARK FOR `dateTime` AS `dateTime` - INTERVAL '4' SECOND,
    PRIMARY KEY (auction, bidder, price, `dateTime`) NOT ENFORCED
) WITH (
    'connector' = 'nexmark',
    'event.type' = 'bid',
    'base-time' = '${BASE_TIME_MILLIS}',
    'first-event-id' = '${FIRST_EVENT_ID}',
    'first-event.rate' = '${TPS}',
    'next-event.rate' = '${TPS}',
    'events.num' = '${EVENTS_NUM}',
    'person.proportion' = '${PERSON_PROPORTION}',
    'auction.proportion' = '${AUCTION_PROPORTION}',
    'bid.proportion' = '${BID_PROPORTION}',
    'keep-alive' = '${KEEP_ALIVE}',
    'stop-at' = '${STOP_AT}',
    'max-emit-speed' = '${MAX_EMIT_SPEED}',
    'occasional-delay.min-sec' = '${OCCASIONAL_DELAY_MIN_SEC}',
    'occasional-delay.sec' = '${OCCASIONAL_DELAY_SEC}',
    'prob-delayed-event' = '${PROB_DELAYED_EVENT}',
    'out-of-order-group-size' = '${OUT_OF_ORDER_GROUP_SIZE}',
    'num-in-flight-auctions' = '${NUM_IN_FLIGHT_AUCTIONS}',
    'scan.watermark.emit.strategy' = 'on-event',
    'scan.watermark.idle-timeout' = '30s',
    'scan.watermark.alignment.group' = 'nexmark-events',
    'scan.watermark.alignment.max-drift' = '1s',
    'scan.watermark.alignment.update-interval' = '200ms'
);

CREATE TABLE bid_modified_src (
    id BIGINT,
    auction BIGINT,
    bidder BIGINT,
    price BIGINT,
    channel VARCHAR,
    url VARCHAR,
    `dateTime` TIMESTAMP(3),
    extra VARCHAR,
    WATERMARK FOR `dateTime` AS `dateTime` - INTERVAL '4' SECOND,
    PRIMARY KEY (id) NOT ENFORCED
) WITH (
    'connector' = 'nexmark',
    'event.type' = 'bid',
    'base-time' = '${BASE_TIME_MILLIS}',
    'first-event-id' = '${FIRST_EVENT_ID}',
    'first-event.rate' = '${TPS}',
    'next-event.rate' = '${TPS}',
    'events.num' = '${EVENTS_NUM}',
    'person.proportion' = '${PERSON_PROPORTION}',
    'auction.proportion' = '${AUCTION_PROPORTION}',
    'bid.proportion' = '${BID_PROPORTION}',
    'keep-alive' = '${KEEP_ALIVE}',
    'stop-at' = '${STOP_AT}',
    'max-emit-speed' = '${MAX_EMIT_SPEED}',
    'occasional-delay.min-sec' = '${OCCASIONAL_DELAY_MIN_SEC}',
    'occasional-delay.sec' = '${OCCASIONAL_DELAY_SEC}',
    'prob-delayed-event' = '${PROB_DELAYED_EVENT}',
    'out-of-order-group-size' = '${OUT_OF_ORDER_GROUP_SIZE}',
    'num-in-flight-auctions' = '${NUM_IN_FLIGHT_AUCTIONS}',
    'scan.watermark.emit.strategy' = 'on-event',
    'scan.watermark.idle-timeout' = '30s',
    'scan.watermark.alignment.group' = 'nexmark-events',
    'scan.watermark.alignment.max-drift' = '1s',
    'scan.watermark.alignment.update-interval' = '200ms'
);
