/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.github.nexmark.flink.generator;

import com.github.nexmark.flink.generator.model.AuctionGenerator;
import com.github.nexmark.flink.generator.model.PersonGenerator;
import com.github.nexmark.flink.model.Bid;
import com.github.nexmark.flink.model.Event;
import com.github.nexmark.flink.generator.model.BidGenerator;

import java.io.Serializable;
import java.util.Iterator;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.PriorityQueue;
import java.util.SplittableRandom;

import static org.apache.flink.util.Preconditions.checkNotNull;


/**
 * A generator for synthetic events. We try to make the data vaguely reasonable. We also ensure most
 * primary key/foreign key relations are correct. Eg: a {@link Bid} event will usually have valid
 * auction and bidder ids which can be joined to already-generated Auction and Person events.
 *
 * <p>To help with testing, we generate timestamps relative to a given {@code baseTime}. Each new
 * event is given a timestamp advanced from the previous timestamp by {@code interEventDelayUs} (in
 * microseconds). The event stream is thus fully deterministic and does not depend on wallclock
 * time.
 */
public class NexmarkGenerator implements Iterator<NexmarkGenerator.NextEvent>, Serializable {

  /**
   * The next event and its various timestamps. Ordered by increasing wallclock timestamp, then
   * (arbitrary but stable) event hash order.
   */
  public static class NextEvent implements Comparable<NextEvent> {
    /** When, in wallclock time, should this event be emitted? */
    public final long wallclockTimestamp;

    /** When, in event time, should this event be considered to have occured? */
    public final long eventTimestamp;

    /** The event itself. */
    public final Event event;

    /** The minimum of this and all future event timestamps. */
    public final long watermark;

    public NextEvent(long wallclockTimestamp, long eventTimestamp, Event event, long watermark) {
      this.wallclockTimestamp = wallclockTimestamp;
      this.eventTimestamp = eventTimestamp;
      this.event = event;
      this.watermark = watermark;
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) {
        return true;
      }
      if (o == null || getClass() != o.getClass()) {
        return false;
      }

      NextEvent nextEvent = (NextEvent) o;

      return (wallclockTimestamp == nextEvent.wallclockTimestamp
          && eventTimestamp == nextEvent.eventTimestamp
          && watermark == nextEvent.watermark
          && event.equals(nextEvent.event));
    }

    @Override
    public int hashCode() {
      return Objects.hash(wallclockTimestamp, eventTimestamp, watermark, event);
    }

    @Override
    public int compareTo(NextEvent other) {
      int i = Long.compare(wallclockTimestamp, other.wallclockTimestamp);
      if (i != 0) {
        return i;
      }
      return Integer.compare(event.hashCode(), other.event.hashCode());
    }
  }

  private final SplittableRandom random = new SplittableRandom();

  /**
   * Configuration to generate events against.
   */
  private GeneratorConfig config;

  /** Number of raw events generated by this generator. */
  private long generatedEventsCountSoFar;

  /** Number of events emitted by this generator. */
  private long emittedEventsCountSoFar;

  /** Wallclock time at which we emitted the first event (ms since epoch). Initially -1. */
  private long wallclockBaseTime;

  /** Events pending emission, ordered by their wallclock release timestamp. */
  private final PriorityQueue<NextEvent> pendingEvents;

  /** The max events that the generator will generate and emit. */
  private final long maxEvents;

  private final double probDelayedEvent;
  private final long occasionalDelayMinMs;
  private final long occasionalDelayMaxMs;

  public NexmarkGenerator(GeneratorConfig config, long eventsCountSoFar, long wallclockBaseTime) {
    this(config, eventsCountSoFar, eventsCountSoFar, wallclockBaseTime, new PriorityQueue<>());
  }

  private NexmarkGenerator(
      GeneratorConfig config,
      long generatedEventsCountSoFar,
      long emittedEventsCountSoFar,
      long wallclockBaseTime,
      PriorityQueue<NextEvent> pendingEvents) {
    checkNotNull(config);
    this.config = config;
    this.generatedEventsCountSoFar = generatedEventsCountSoFar;
    this.emittedEventsCountSoFar = emittedEventsCountSoFar;
    this.wallclockBaseTime = wallclockBaseTime;
    this.pendingEvents = new PriorityQueue<>(pendingEvents);
    this.maxEvents = config.stopAtEvent < 0 ? config.maxEvents : Math.min(config.stopAtEvent, config.maxEvents);
    this.probDelayedEvent = clampProbability(config.getProbDelayedEvent());
    this.occasionalDelayMinMs = secondsToMillis(config.getOccasionalDelayMinSec());
    this.occasionalDelayMaxMs = Math.max(occasionalDelayMinMs, secondsToMillis(config.getOccasionalDelaySec()));
  }

  /** Create a fresh generator according to {@code config}. */
  public NexmarkGenerator(GeneratorConfig config) {
    this(config, 0, -1);
  }

  /** Return a deep copy of this generator. */
  public NexmarkGenerator copy() {
    checkNotNull(config);
    return new NexmarkGenerator(
        config,
        generatedEventsCountSoFar,
        emittedEventsCountSoFar,
        wallclockBaseTime,
        pendingEvents);
  }

  /**
   * Return the current config for this generator.
   */
  public GeneratorConfig getCurrentConfig() {
    return config;
  }

  /**
   * Return the next 'event id'. Though events don't have ids we can simulate them to help with
   * bookkeeping.
   */
  public long getNextEventId() {
    return config.firstEventId + config.nextAdjustedEventNumber(generatedEventsCountSoFar);
  }

  @Override
  public boolean hasNext() {
    return emittedEventsCountSoFar < maxEvents;
  }

  /**
   * Return the next event. The outer timestamp is in wallclock time and corresponds to when the
   * event should fire. The inner timestamp is in event-time and represents the time the event is
   * purported to have taken place in the simulation.
   */
  public NextEvent nextEvent() {
    if (!hasNext()) {
      throw new NoSuchElementException("No more events available");
    }
    if (wallclockBaseTime < 0) {
      wallclockBaseTime = System.currentTimeMillis();
    }

    while (generatedEventsCountSoFar < maxEvents) {
      NextEvent readyEvent = pendingEvents.peek();
      if (readyEvent != null && readyEvent.wallclockTimestamp <= nextRawEventWallclockTimestamp()) {
        emittedEventsCountSoFar++;
        return pendingEvents.poll();
      }

      NextEvent rawEvent = nextRawEvent();
      pendingEvents.offer(applyOccasionalDelay(rawEvent));
    }

    NextEvent finalEvent = pendingEvents.poll();
    if (finalEvent == null) {
      throw new NoSuchElementException("No more events available");
    }
    emittedEventsCountSoFar++;
    return finalEvent;
  }

  @Override
  public NexmarkGenerator.NextEvent next() {
    return nextEvent();
  }

  @Override
  public void remove() {
    throw new UnsupportedOperationException();
  }

  /** Return an estimate of fraction of output consumed. */
  public double getFractionConsumed() {
    if (maxEvents == 0) {
      return 1.0;
    }
    return (double) emittedEventsCountSoFar / maxEvents;
  }

  /**
   * Gets Number of events generated by this generator.
   */
  public long getEventsCountSoFar() {
    return emittedEventsCountSoFar;
  }

  public long getWallclockBaseTime() {
    return wallclockBaseTime;
  }

  @Override
  public String toString() {
    return String.format(
        "Generator{config:%s; generatedEventsCountSoFar:%d; emittedEventsCountSoFar:%d; wallclockBaseTime:%d}",
        config, generatedEventsCountSoFar, emittedEventsCountSoFar, wallclockBaseTime);
  }

  private NextEvent nextRawEvent() {
    // When, in event time, we should generate the event. Monotonic.
    long eventTimestamp =
        config.timestampForEvent(config.nextEventNumber(generatedEventsCountSoFar));
    // When, in event time, the event should say it was generated. Depending on outOfOrderGroupSize
    // may have local jitter.
    long adjustedEventTimestamp =
        config.timestampForEvent(config.nextAdjustedEventNumber(generatedEventsCountSoFar));
    // The minimum of this and all future adjusted event timestamps. Accounts for jitter in
    // the event timestamp.
    long watermark =
        config.timestampForEvent(config.nextEventNumberForWatermark(generatedEventsCountSoFar));
    // When, in wallclock time, we should emit the event.
    long wallclockTimestamp = wallclockBaseTime + (eventTimestamp - getCurrentConfig().baseTime);

    long newEventId = getNextEventId();
    long rem = newEventId % config.totalProportion;
    java.util.SplittableRandom eventRandom = new java.util.SplittableRandom(newEventId);

    Event event;
    if (rem < config.personProportion) {
      event =
          new Event(
              PersonGenerator.nextPerson(
                  newEventId, eventRandom, adjustedEventTimestamp, config));
    } else if (rem < config.personProportion + config.auctionProportion) {
      event =
          new Event(
              AuctionGenerator.nextAuction(
                  generatedEventsCountSoFar, newEventId, eventRandom, adjustedEventTimestamp, config));
    } else {
      event =
          new Event(BidGenerator.nextBid(newEventId, eventRandom, adjustedEventTimestamp, config));
    }

    generatedEventsCountSoFar++;
    return new NextEvent(wallclockTimestamp, adjustedEventTimestamp, event, watermark);
  }

  private long nextRawEventWallclockTimestamp() {
    long eventTimestamp = config.timestampForEvent(config.nextEventNumber(generatedEventsCountSoFar));
    return wallclockBaseTime + (eventTimestamp - getCurrentConfig().baseTime);
  }

  private NextEvent applyOccasionalDelay(NextEvent event) {
    if (!shouldDelay(event.event) || probDelayedEvent <= 0.0 || random.nextDouble() >= probDelayedEvent) {
      return event;
    }

    long delayMs = randomDelayMs();
    if (delayMs <= 0) {
      return event;
    }

    return new NextEvent(
        event.wallclockTimestamp + delayMs,
        event.eventTimestamp,
        event.event,
        event.watermark);
  }

  private boolean shouldDelay(Event event) {
    return event.type == Event.Type.AUCTION || event.type == Event.Type.BID;
  }

  private long randomDelayMs() {
    if (occasionalDelayMaxMs <= occasionalDelayMinMs) {
      return occasionalDelayMinMs;
    }
    long spread = occasionalDelayMaxMs - occasionalDelayMinMs;
    return occasionalDelayMinMs + random.nextLong(spread + 1);
  }

  private static long secondsToMillis(long delaySeconds) {
    if (delaySeconds <= 0) {
      return 0L;
    }
    if (delaySeconds > Long.MAX_VALUE / 1000L) {
      return Long.MAX_VALUE;
    }
    return delaySeconds * 1000L;
  }

  private static double clampProbability(double value) {
    if (Double.isNaN(value)) {
      return 0.0;
    }
    return Math.max(0.0, Math.min(1.0, value));
  }
}
